### ISSUE TITLE
使用中遇到问题，显示空白，无报错。

### ISSUE THREAD

**Issue by M69W** [Lanseria/vue-pdf-useinvite#1]
在这个框架 [vue-vben-admin](https://github.com/anncwb/vue-vben-admin) 使用，
之前在某个旧版本能使用
https://github.com/anncwb/vue-vben-admin/issues/1064 

更新后，显示空白，无报错。

如果把插件抽离出来使用，使用正常。
![image](https://user-images.githubusercontent.com/15809201/130110942-127dadc2-13cb-4e4b-9afd-3df9904da471.png)

![image](https://user-images.githubusercontent.com/15809201/130110724-7336f0a1-97d5-4336-8e68-8e82103ba7a1.png)
![image](https://user-images.githubusercontent.com/15809201/130111170-43841d1e-98d6-461a-a77f-5b87bc57b35d.png)

```
"pdf-lib": "^1.16.0",
"pdfjs-dist": "2.10.377",
```
[归档.zip](https://github.com/Lanseria/vue-pdf-useinvite/files/7016368/default.zip)

**Comment by lanseria** [comment]
我认为你还是抽离出来用好了，这是个参考示例库

**Comment by M69W** [comment]
可以，感谢提供示例。
