### ISSUE TITLE
引用错误：Warning: Setting up fake worker.

### ISSUE THREAD

**Issue by t-sinbo** [Lanseria/vue-pdf-useinvite#3]
![image](https://user-images.githubusercontent.com/30678067/153520143-19ff676a-60d9-45a8-b1c0-51ac1aacc4f1.png)
出现问题如上
最近突然出现引用这个库错误，之前是正常的

![image](https://user-images.githubusercontent.com/30678067/153520541-2a08d283-6497-436f-ba3d-4bf691700201.png)
应该是这个引用 建议修改

**Comment by lanseria** [comment]
@t-sinbo 知乎的 unpkg 被屏蔽了我这里直接固定版本与与国外的unpkg了,如果要修改你可以自己 fork 本项目

**Comment by t-sinbo** [comment]
> 

我直接使用你现在发布这个版本可以吗？

**Comment by lanseria** [comment]
> > 
> 
> 我直接使用你现在发布这个版本可以吗？

没问题
